CREATE PROCEDURE SP_LISTAR_INCIDENCIAS
(
    @TIPO INT = NULL,
    @SUBTIPO INT = NULL,
    @FECHA_DESDE DATETIME = NULL,
    @FECHA_HASTA DATETIME = NULL,
    @LIMIT INT = 50
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT TOP (@LIMIT)
        ID_INCIDENCIA,
        ID_TIPO,
        ID_SUBTIPO,
        FECHA_INCIDENCIA,
        DESCRIPCION,
        DIRECCION_REFERENCIA
    FROM INCIDENCIA
    WHERE
        ESTADO = 1
        AND (@TIPO IS NULL OR ID_TIPO = @TIPO)
        AND (@SUBTIPO IS NULL OR ID_SUBTIPO = @SUBTIPO)
        AND (@FECHA_DESDE IS NULL OR FECHA_INCIDENCIA >= @FECHA_DESDE)
        AND (@FECHA_HASTA IS NULL OR FECHA_INCIDENCIA <= @FECHA_HASTA)
    ORDER BY FECHA_INCIDENCIA DESC;
END