CREATE PROCEDURE [dbo].[SP_LISTAR_TIPOS_INCIDENCIA]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        ID_TIPO,
        NOMBRE,
        DESCRIPCION
    FROM dbo.TIPO_INCIDENCIA
    ORDER BY NOMBRE;
END;
GO