CREATE PROCEDURE [dbo].[SP_LOGIN_USUARIO]
    @CORREO NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        U.ID_USUARIO,
        U.CONTRASENA_HASH
    FROM 
        USUARIO U
    WHERE 
        EMAIL = @CORREO;
END;
