CREATE PROCEDURE [dbo].[SP_LISTAR_INCIDENCIAS]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        I.ID_INCIDENCIA,
        I.ID_TIPO,
        T.NOMBRE      AS TIPO_NOMBRE,
        I.ID_SUBTIPO,
        S.NOMBRE      AS SUBTIPO_NOMBRE,
        I.FECHA_INCIDENCIA,
        I.LATITUD,
        I.LONGITUD,
        I.DIRECCION_REFERENCIA,
        I.DESCRIPCION,
        I.FOTO_URL,
        I.ESTADO
    FROM dbo.INCIDENCIA AS I
    LEFT JOIN dbo.TIPO_INCIDENCIA   AS T ON T.ID_TIPO = I.ID_TIPO 
    LEFT JOIN dbo.SUBTIPO_INCIDENCIA AS S ON S.ID_SUBTIPO = I.ID_SUBTIPO
    ORDER BY I.FECHA_REGISTRO DESC;
END;
GO