CREATE PROCEDURE SP_LISTAR_INCIDENCIAS_POR_USUARIO
(
    @UsuarioId INT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        ID_INCIDENCIA,
        ID_TIPO,
        ID_SUBTIPO,
        FECHA_INCIDENCIA
    FROM INCIDENCIA
    WHERE ID_USUARIO = @UsuarioId
    ORDER BY FECHA_REGISTRO DESC;
END
