CREATE PROCEDURE [dbo].[SP_LISTAR_SUBTIPOS]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        ID_SUBTIPO,
        ID_TIPO,
        NOMBRE,
        NIVEL
    FROM dbo.SUBTIPO_INCIDENCIA
    ORDER BY NIVEL, NOMBRE;
END;
GO