CREATE PROCEDURE [dbo].[SP_OBTENER_CUENTA_POR_ID]
    @ID_USUARIO INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        ID_USUARIO,
        NOMBRE,
        EMAIL,
        ROL
    FROM dbo.USUARIO
    WHERE ID_USUARIO = @ID_USUARIO;
END;
