CREATE PROCEDURE [dbo].[SP_OBTENER_SUBTIPO_POR_ID]
    @ID_SUBTIPO INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        ID_SUBTIPO,
        ID_TIPO,
        NOMBRE,
        NIVEL
    FROM dbo.SUBTIPO_INCIDENCIA
    WHERE ID_SUBTIPO = @ID_SUBTIPO;
END;
GO