CREATE PROCEDURE [dbo].[SP_OBTENER_TIPO_POR_ID]
    @ID_TIPO INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        ID_TIPO,
        NOMBRE,
        DESCRIPCION
    FROM dbo.TIPO_INCIDENCIA
    WHERE ID_TIPO = @ID_TIPO;
END;
GO